name: CI Pipeline

on:
  push:
    branches:
      - '**'   # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Running CI pipeline..."

      - name: Print hello message
        run: echo "Hello, GitHub Actions!"
